### ISSUE TITLE
PageTOC插件目录加载问题

### ISSUE THREAD

**Issue by Zhaoyang-Song** [Gk0Wk/TiddlySeq#1]
TiddlyWiki在使用PageTOC插件生成目录时，如果目录过长，无法滑动拉至更往后的内容。

举个例子，假设h1有100个，可能屏幕上只显示前20个，无法通过上下滑动或者其他办法得到目录后面的内容，也就无法完成查看和跳转。

此加载问题的文件类型是Markdown，非TW原生格式。（并未试过原生格式是否存在该问题）

**Comment by fcnaud** [comment]
我也遇到了类似的问题，你修改下样式文件就可以了，给这个div加个高度。

1. 打开插件的样式文件

![image](https://user-images.githubusercontent.com/9380918/188069013-a044fcca-2e52-4c66-96ca-7326ddf1c83b.png)

2. 找到这里，给这个class添加如下内容

![image](https://user-images.githubusercontent.com/9380918/188069148-8f606804-4d32-419d-a946-b71b8cd45944.png)

```
	height: 300px;
	overflow: auto;
```

3. 最终结果，其他的地方也类似

![image](https://user-images.githubusercontent.com/9380918/188069382-2d3b1df3-4085-410d-a4fa-a646a0579133.png)

**Comment by Gk0Wk** [comment]
TW 原生插件写起来还是太麻烦了，后面计划换成用 React 写，所以这个暂时就不修了。

**Comment by Gk0Wk** [comment]
不对呀，之前似乎已经修复了哈哈：

```css
.gk0wk-tiddlertoc-viewbuttonpopup {
  border-radius: 3px;
  background: <<colour page-background>>;
  width: min(90vw, 300px);
  <<box-shadow "#00000070 0 2px 6px">>
  filter: contrast(90%);
  padding: 0;
  overflow-y: auto;
  max-height: 80vh;
}
```
